[package]
name = "clarity-types-native"
version = "1.0.3"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
clarity-types = { path = "../clarity-types-rs" }

[build-dependencies]
napi-build = "2"
