/* auto-generated by NAPI-RS */
/* eslint-disable */

export function parse(contractPath: string, traitDir?: string | undefined | null, contractName?: string | undefined | null, clarityVersion?: "clarity1" | "clarity2" | undefined): string

export function parseMem(contractSource: string, traits: Record<string, string>, contractName: string, clarityVersion?: "clarity1" | "clarity2" | undefined): string

